{
 "title": "Breast Cancer Risk Analysis & Monitoring",
 "time": { "from": "2026-03-23T22:40:36.948Z", "to": "2026-03-23T22:45:36.948Z" },
 "templating": {
  "list": [
   { "name": "threshold", "label": "Clinical Threshold", "query": "0.1, 0.2, 0.3, 0.5, 0.8" }
  ]
 },
 "panels": [
  {
   "title": "Clinical Workload",
   "type": "bargauge",
   "description": "Calculates how many patients require immediate attention based on the selected probability threshold.",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "grafana-labs-cancer",
     "rawSql": "SELECT \n  'Pacientes em Risco Alto' as categoria,\n  COUNT(*) as total\nFROM cancer_data\nWHERE probability > ${threshold};\n"
    }
   ]
  },
  {
   "title": "Prediction Precision ",
   "type": "gauge",
   "description": "Percentage of high-risk alerts that are confirmed malignant cases. A lower precision is expected when prioritizing high sensitivity to ensure patient safety.",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana-labs-cancer",
     "rawSql": "SELECT \n  (COUNT(*) FILTER (WHERE probability > ${threshold} AND diagnosis = 1)::float / \n   COUNT(*) FILTER (WHERE probability > ${threshold})) * 100 as precision\nFROM cancer_data;"
    }
   ]
  },
  {
   "title": "Clinical Sensitivity ",
   "type": "gauge",
   "description": "Measures the model's ability to correctly identify all malignant cases. A sensitivity of 100% means zero missed cancers. At a 0.2 threshold, we prioritize capturing more potential cases even if it increases false alarms.",
   "gridPos": { "h": 12, "w": 5, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana-labs-cancer",
     "rawSql": "SELECT \n  (COUNT(*) FILTER (WHERE probability > ${threshold} AND diagnosis = 1)::float / \n   COUNT(*) FILTER (WHERE diagnosis = 1)) * 100 as recall\nFROM cancer_data;\n"
    }
   ]
  },
  {
   "title": "Model Performance: Confusion Matrix",
   "type": "table",
   "description": "Detailed breakdown of prediction accuracy. Highlighting False Negatives (Missed Cases) in red as the most critical clinical failure, and False Positives (False Alarms) in orange.",
   "gridPos": { "h": 12, "w": 11, "x": 12, "y": 7 },
   "targets": [
    {
     "dataset": "grafana-labs-cancer",
     "rawSql": "SELECT \n  CASE \n    WHEN diagnosis = 1 AND probability > ${threshold} THEN '✅ True Positive'\n    WHEN diagnosis = 0 AND probability <= ${threshold} THEN '✅ True Negative'\n    WHEN diagnosis = 0 AND probability > ${threshold} THEN '❌ False Positive'\n    WHEN diagnosis = 1 AND probability <= ${threshold} THEN '🚨 False Negative'\n  END AS classification,\n  COUNT(*) as total\nFROM cancer_data\nGROUP BY classification;\n"
    }
   ]
  },
  {
   "title": "Benign VS Malignant",
   "type": "barchart",
   "description": "Diagnostic Distribution",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "grafana-labs-cancer",
     "rawSql": "SELECT \n    CASE \n        WHEN diagnosis = 0 THEN 'Benign'\n        WHEN diagnosis = 1 THEN 'Malignant'\n        ELSE 'Indefinido'\n    END AS diagnosis_label,\n    COUNT(*) as total \nFROM cancer_data \nGROUP BY diagnosis;\n"
    }
   ]
  },
  {
   "title": "Model Confidence Distribution",
   "type": "histogram",
   "description": "Visualizes how the model separates probabilities. Ideally, benign cases (Green) cluster near 0.0 and malignant cases (Red) near 1.0. The overlap area represents the 'uncertainty zone' where clinical thresholding is most critical.",
   "gridPos": { "h": 13, "w": 16, "x": 7, "y": 19 },
   "targets": [
    {
     "dataset": "grafana-labs-cancer",
     "rawSql": "SELECT \n  probability,\n  CASE WHEN diagnosis = 0 THEN 'Benign' ELSE 'Malignant' END AS status\nFROM cancer_data;\n\n\n"
    }
   ]
  },
  {
   "title": "Distribution of Mean Radius by Diagnosis",
   "type": "histogram",
   "description": "This histogram displays the distribution of the 'radius_mean' feature for both benign and malignant cases. It highlights how smaller radius values correlate with benign samples (Green), while larger values typically indicate malignant cases (Red), showing the clear separation between the two categories.",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 32 },
   "targets": [
    {
     "dataset": "grafana-labs-cancer",
     "rawSql": "SELECT \n    radius_mean,\n    CASE WHEN diagnosis = 0 THEN 'Benign' ELSE 'Malignant' END AS status\nFROM cancer_data;\n"
    }
   ]
  }
 ]
}